version: "3.9"

services:
  db:
    container_name: acourse_tag_bookmark_cart_service_db
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./pkg/database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - db_vol:/data/db
    ports:
      - 27018:${DB_PORT}
    networks:
      default:
        ipv4_address: 192.168.144.21

  app:
    container_name: acourse_tag_bookmark_cart_service_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:${APP_PORT}
    restart: on-failure
    volumes:
      - app_vol:/app
    networks:
      default:
        ipv4_address: 192.168.144.20
    depends_on:
      - db

volumes:
  app_vol:
  db_vol:

networks:
  default:
      external: true
      name: acourse_bridge_network
#    driver: bridge